language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
script: npm run coverage
after_success:
  - npm install -g codeclimate-test-reporter
  - npm install -g coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
  - coveralls < ./coverage/lcov.info
before_script:
  - npm run bundle
